### ISSUE TITLE
[FLI-964] Support Intel Macs

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt-client-sdks#249]
Re: #248

We should build an engine for Intel Macs and be able to load it for all the SDKs

## TODO

- [X] Setup CI to build/package Intel Mac engine
- [ ] Support in Java SDK
- [ ] Support in Go SDK
- [ ] Support in Node SDK
- [ ] Support in Python SDK
- [ ] Test
- [ ] Also add supported OS/Architectures to all READMEs

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-964](https://linear.app/flipt/issue/FLI-964/support-intel-macs)</sub>
