### ISSUE TITLE
Package + Distribute

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt-client-sdks#38]
Figure out how to build and publish native packages instead of requiring users to build from source

## TODO

- [x] Figure out how to package per ecosystem
  - [x] Ruby
  - [x] Go
  - [x] Node
  - [x] Python
- [x] Publish to each ecosystem (gitea packages for testing)
  - [x] Ruby
  - [x] Go
  - [x] Node
  - [x] Python
- [x] Publish to real package registries for each ecosystem
  - [x] Ruby
  - [x] Go
  - [x] Node
  - [x] Python
- [x] Test
- [x] Update Docs

**Comment by markphelps** [comment]
Done
